description: Running Demucs  Model w/ Bass
exp_name: MSG Demucs Bass
id: msg_demucs_bass
parameters:

  # Model Parameters
  model: 'demucs'
  use_mix: True
  multi_disc: False
  audio_channels: 2

  # Directories
  model_save_dir: '/media/CHONK/data/imputation/saves/saves_demucs_bass_mix/'
  model_load_dir: '/media/CHONK/data/imputation/saves/saves_baseline_drums/'
  train_sources_path: '/media/CHONK/data/imputation/DemucsDataset/SalientSourceTrainDatasetShortenedFolder/'
  valid_sources_path: '/media/CHONK/data/imputation/DemucsDataset/SalientSourceValidationDatasetFolder/'
  # Dataloader parameters
  sample_rate: 44100
  mix_folder: 'mixture'
  segment_duration: 1.0
  verbose: True

  # Training Hyperparameters
  random_seed: 0
  start_epoch: 0
  n_epochs: 4000
  pretrain_epoch: 1000
  validation_steps: 5000
  random_sample : 1200
  checkpoint_interval: 25
  batch_size: 16
  n_cpu: 4
  source: 'bass'
  gpus: [1, 2]

  # Optimizer Hyperparameters
  lr: 0.0001
  b1: .5
  b2: .9

  #Generator Hyperparameters
  n_mel_channels: 80
  ngf: 32
  n_residual_layers: 3
  lambda_feat: 10
  lambda_feat_spec: 10
  skip_cxn: True

  #Discriminator Hyperparameters
  num_D: 3
  ndf: 16
  n_layers_D: 4
  downsamp_factor: 4
  n_layers_D_spec: 6



start_time: '20200225_20_43_41'
