description: Running Baseline Model
exp_name: MSGBaseline
id: msg_baseline
parameters:

  # Directories
  model_load_path: '/home/nas6354/evaluation/checkpoints/demucs_baseline/99netG.pt'
  dataset_path: '/home/nas6354/datasets/SalientSourceTestDatasetFolder/'
  log_dir: '/drive/MelGan-Imputation/eval_saves/'
  run_id: demucs_baseline

  source: 'bass'
  model: 'demucs'

  #Generator Hyperparameters
  audio_channels: 1
  segment_duration: 1
  sample_rate: 44100
  skip_cxn: True
  use_mix: False
  gpus: [2]

  hop_len: .1
  random_seed: 0



start_time: '20200225_20_43_41'