description: Running Demucs  Model w/ Bass
exp_name: MSG Demucs Bass
id: msg_demucs_bass
parameters:

  # Model Parameters
  model: 'demucs'
  use_mix: false
  multi_disc: True
  audio_channels: 2
  debug: True
  mono: False
  # Directories
  model_save_dir: '/home/nas6354/saves/demucs_extended_baseline/'
  model_load_dir: '/media/CHONK/data/imputation/saves/saves_baseline_drums/'
  train_sources_path: '/home/nas6354/datasets/SalientSourceTrainDatasetFolder/'
  valid_sources_path: '/home/nas6354/datasets/SalientSourceValidationDatasetFolder/'
  # Dataloader parameters
  sample_rate: 44100
  mix_folder: 'mixture'
  segment_duration: 10
  verbose: True

  # Training Hyperparameters
  random_seed: 0
  start_epoch: 0
  n_epochs: 500
  pretrain_epoch: 50
  validation_steps: 5000
  random_sample : 5030
  checkpoint_interval: 25
  batch_size: 4
  n_cpu: 4
  source: 'bass'
  gpus: [2]

  # Optimizer Hyperparameters
  lr: 0.0001
  b1: .5
  b2: .9

  #Generator Hyperparameters
  n_mel_channels: 80
  ngf: 32
  n_residual_layers: 3
  lambda_feat: 10
  lambda_feat_spec: 10
  skip_cxn: True

  #Discriminator Hyperparameters
  num_D: 3
  ndf: 16
  n_layers_D: 4
  downsamp_factor: 4
  n_layers_D_spec: 6



start_time: '20200225_20_43_41'
