description: Running Baseline Model
exp_name: MSGBaseline
id: msg_baseline
parameters:

  # Directories
  model_load_path: '/home/noah/saves/demucs_test_mod/24netG.pt'
  dataset_path: '/home/boaz/datasets/DemucsDataset/SalientSourceValidationDatasetFolder'
  log_dir: '/home/noah/logs'
  run_id: demucs_baseline

  source: 'bass'
  model: 'demucs'
  random_seed: 0

  #Generator Hyperparameters
  audio_channels: 1
  segment_duration: 1
  sample_rate: 44100
  skip_cxn: True
  use_mix: False
  gpus: [2]

  hop_len: .1
  random_seed: 0



start_time: '20200225_20_43_41'
