description: Running Baseline Model
exp_name: MSGBaseline
id: msg_baseline
parameters:

  # Directories
  model_save_dir: '/drive/development_folder/saves_baseline_bass/'
  model_load_dir: '/drive/development_folder/saves_baseline_bass/'
  train_sources_path: '/drive/DemucsDataset/SalientSourceDrumsTrain/'
  valid_sources_path: '/drive/DemucsDataset/SalientSourceValidationDatasetFolder/'

  # Dataloader parameters
  sample_rate: 44100
  mix_folder: 'mixture'
  segment_duration: 1.0
  verbose: True

  # Training Hyperparameters
  random_seed: 0
  start_epoch: 0 
  n_epochs: 3000
  pretrain_epoch: 0
  validation_steps: 5000
  random_sample : 1200
  checkpoint_interval: 25
  batch_size: 64
  n_cpu: 4
  source: 'bass'

  # Optimizer Hyperparameters
  lr: 0.0001
  b1: .5
  b2: .9

  #Generator Hyperparameters
  n_mel_channels: 80
  ngf: 32
  n_residual_layers: 3
  lambda_feat: 10
  skip_cxn: True

  #Discriminator Hyperparameters
  num_D: 3
  ndf: 16
  n_layers_D: 4
  downsamp_factor: 4



start_time: '20200225_20_43_41'
