description: Running Baseline Model
exp_name: MSGBaseline
id: msg_baseline
parameters:

  # Directories
  model_load_dir: '/drive/MelGan-Imputation/saves_baseline/'
  original_sources_path: '/drive/MelGan-Imputation/datasets/original_test_sources/'
  separated_sources_path: '/drive/MelGan-Imputation/datasets/demucs_test_flattened/'
  log_dir: '/drive/MelGan-Imputation/eval_saves/'
  run_id: 7_7_noah

  load_epoch: 2999

  #Generator Hyperparameters
  n_mel_channels: 80
  ngf: 32
  n_residual_layers: 3
  lambda_feat: 10
  skip_cxn: True




start_time: '20200225_20_43_41'