wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.1
    framework: ignite
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    t:
      1:
      - 1
      - 5
      - 10
      2:
      - 1
      - 5
      - 10
      4: 3.8.10
      5: 0.11.1
      8:
      - 5
b1:
  desc: null
  value: 0.5
b2:
  desc: null
  value: 0.9
batch_size:
  desc: null
  value: 16
checkpoint_interval:
  desc: null
  value: 25
downsamp_factor:
  desc: null
  value: 4
gpus:
  desc: null
  value:
  - 1
  - 2
lambda_feat:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.0001
mix_folder:
  desc: null
  value: mixture
model_load_dir:
  desc: null
  value: /media/CHONK/data/imputation/saves_baseline_bass/
model_save_dir:
  desc: null
  value: /media/CHONK/data/imputation/saves_baseline_bass/
n_cpu:
  desc: null
  value: 4
n_epochs:
  desc: null
  value: 3000
n_layers_D:
  desc: null
  value: 4
n_mel_channels:
  desc: null
  value: 80
n_residual_layers:
  desc: null
  value: 3
ndf:
  desc: null
  value: 16
ngf:
  desc: null
  value: 32
num_D:
  desc: null
  value: 3
pretrain_epoch:
  desc: null
  value: 0
random_sample:
  desc: null
  value: 1200
random_seed:
  desc: null
  value: 0
sample_rate:
  desc: null
  value: 44100
segment_duration:
  desc: null
  value: 1.0
skip_cxn:
  desc: null
  value: true
source:
  desc: null
  value: bass
start_epoch:
  desc: null
  value: 0
train_sources_path:
  desc: null
  value: /media/CHONK/data/imputation/DemucsDataset/SalientSourceTrainDatasetShortenedFolder/
valid_sources_path:
  desc: null
  value: /media/CHONK/data/imputation/DemucsDataset/SalientSourceValidationDatasetFolder/
validation_steps:
  desc: null
  value: 5000
verbose:
  desc: null
  value: true
